### ISSUE TITLE
Bootstrap 4 Courses to be Completed

### ISSUE THREAD

**Issue by iwebgit** [iwebgit/iWeb-Bootstrap-4-Basic-Template#2]
## TODO

*Courses left to complete Bootstrap 4 track*

* [ ] Getting to Know Bootstrap 4
* [ ] Responsive Layouts With the Bootstrap Grid
* [ ] Using Bootstrap Components
* [ ] Building Forms With Bootstrap
🥇 🚶 🐎 🌊 📦 

cc@iwebgit
